project_name: paladin
release:
  github:
    owner: Zeerg
    name: paladin
  name_template: '{{.Tag}}'
scoop:
  name: paladin
  commit_author:
    name: goreleaserbot
    email: goreleaser@carlosbecker.com
builds:
- id: paladin
  goos:
  - linux
  goarch:
  - amd64
  goarm:
  - "6"
  targets:
  - linux_amd64
  dir: .
  main: .
  ldflags:
  - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
    -X main.builtBy=goreleaser
  binary: paladin
  lang: go
archives:
- id: default
  builds:
  - paladin
  name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm
    }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}'
  format: tar.gz
  files:
  - licence*
  - LICENCE*
  - license*
  - LICENSE*
  - readme*
  - README*
  - changelog*
  - CHANGELOG*
snapshot:
  name_template: '{{ .Tag }}-SNAPSHOT-{{ .ShortCommit }}'
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'
  algorithm: sha256
dist: dist
env_files:
  github_token: ~/.config/goreleaser/github_token
  gitlab_token: ~/.config/goreleaser/gitlab_token
  gitea_token: ~/.config/goreleaser/gitea_token
github_urls:
  download: https://github.com
gitlab_urls:
  download: https://gitlab.com
